### ISSUE TITLE
Is managesieve actually triggered?

### ISSUE THREAD

**Issue by lukas-mika** [arodier/Roundcube-Plugins#18]
Hi Andre,

thank you so much for your awesome work. Maybe you noticed, that I copied and modified your identiteam plugin already (I'd rather like to fork it, but you would need to have this plugin in a separate repository).
Now I'm working on integrating the vacation_sieve plugin, but it seems like I'm missing something.
I tried the following config:

``` php
'msg_format' => 'html',
'working_hours' => array(8,18),
'debug' => true,
'transfer' => array(
    'mode' =>  'managesieve',
    'ms_activate_script' => true,
    'host' => 'localhost',
    'port'   => '4190',
    'usetls' => false,
    'path' => '/var/vmail/<logon>/sieve/managesieve.sieve',
    'sievecbin' => '',
)
```

However, whenever I open the interface within roundcube, the error logs state that the current rule cannot be accessed and whenever I try to save, the logs state that the rule cannot be saved in this file.
Indeed the file does exist and is writable by dovecot's internal user and managesieve does work on this port, too (checked with the sieverules plugin and iptables accepts all calls to loopback).
So my initial thought is that maybe the plugin cannot access managesieve for whatever reason.

Can you tell me how to find out, what is going wrong here?

Cheers,
dim-0

**Comment by lukas-mika** [comment]
Alright - got it. Next time I will read the config lines more carefully.
When using managesieve, 'path' needs to have the script name.

``` php
'path' => 'managesieve'
```

That did the trick ;)

**Comment by arodier** [comment]
great. Sorry to have missed your message.
