### ISSUE TITLE
Support sieve servers with no date support

### ISSUE THREAD

**Issue by a-schild** [arodier/Roundcube-Plugins#8]
Cyrus has no support for RFC 5260 (Will be in cyrus 2.5)
http://cyrusimap.web.cmu.edu/mediawiki/index.php/RoadMap

Horde/IMP do handle date restrictions via regex in this form

```
if header :regex "Received" "^.*(2013) (\\(.*\\) )?..:..:.. (\\(.*\\) )?((\\+|\\-)[[:digit:]]{4}|.{1,5})( \\(.*\\))?$" {
if header :regex "Received" "^.*(May) (\\(.*\\) )?.... (\\(.*\\) )?..:..:.. (\\(.*\\) )?((\\+|\\-)[[:digit:]]{4}|.{1,5})( \\(.*\\))?$" {
if header :regex "Received" "^.*(23|24|25|26|27|28|29|30) (\\(.*\\) )?... (\\(.*\\) )?.... (\\(.*\\) )?..:..:.. (\\(.*\\) )?((\\+|\\-)[[:digit:]]{4}|.{1,5})( \\(.*\\))?$" {
```

**Comment by arodier** [comment]
I focused on dovecot, because it has a good support of sieve.

Adding a layer of complexity to implement something that the web server does not is not a good aproach.
